# Translations template for barbican.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the barbican project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: barbican 2015.1.dev123\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-13 06:11+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: barbican/api/__init__.py:62
msgid "Read Error"
msgstr ""

#: barbican/api/__init__.py:72
msgid "Malformed JSON"
msgstr ""

#: barbican/api/__init__.py:106
msgid ""
"{operation} attempt not allowed - please review your user/project "
"privileges"
msgstr ""

#: barbican/api/__init__.py:116
msgid "{operation} failure seen - please contact site administrator."
msgstr ""

#: barbican/api/__init__.py:120
msgid "{operation} issue seen - {reason}."
msgstr ""

#: barbican/api/controllers/__init__.py:97
msgid "System"
msgstr ""

#: barbican/api/controllers/__init__.py:129
msgid "Unexpected content type: {type}. Expected content types are: {expected}"
msgstr ""

#: barbican/api/controllers/acls.py:31
msgid "Not Found. Sorry no ACL found for given {0}."
msgstr ""

#: barbican/api/controllers/acls.py:37
msgid "Not Found. Sorry no ACL found for given id."
msgstr ""

#: barbican/api/controllers/acls.py:42
msgid "Existing ACL cannot be updated with POST method."
msgstr ""

#: barbican/api/controllers/acls.py:51
msgid "Existing ACL's operation cannot be updated."
msgstr ""

#: barbican/api/controllers/acls.py:73
msgid "SecretACL retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:88
msgid "A SecretACL Update"
msgstr ""

#: barbican/api/controllers/acls.py:122
msgid "SecretACL deletion"
msgstr ""

#: barbican/api/controllers/acls.py:162
msgid "SecretACL(s) retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:171
msgid "SecretACL(s) creation"
msgstr ""

#: barbican/api/controllers/acls.py:220
msgid "SecretACL(s) Update"
msgstr ""

#: barbican/api/controllers/acls.py:277
msgid "SecretACL(s) deletion"
msgstr ""

#: barbican/api/controllers/acls.py:316
msgid "ContainerACL retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:331
msgid "A ContainerACL Update"
msgstr ""

#: barbican/api/controllers/acls.py:364
msgid "ContainerACL deletion"
msgstr ""

#: barbican/api/controllers/acls.py:406
msgid "ContainerACL(s) retrieval"
msgstr ""

#: barbican/api/controllers/acls.py:418
msgid "ContainerACL(s) creation"
msgstr ""

#: barbican/api/controllers/acls.py:469
msgid "ContainerACL(s) Update"
msgstr ""

#: barbican/api/controllers/acls.py:527
msgid "ContainerACL(s) deletion"
msgstr ""

#: barbican/api/controllers/cas.py:32
msgid "Not Found. CA not found."
msgstr ""

#: barbican/api/controllers/cas.py:39
msgid "Cannot set CA as a preferred CA as it is not a project CA."
msgstr ""

#: barbican/api/controllers/cas.py:71
msgid "Certificate Authority retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:78
msgid "CA Signing Cert retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:86
msgid "CA Cert Chain retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:94
msgid "CA projects retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:111
msgid "Add CA to project"
msgstr ""

#: barbican/api/controllers/cas.py:139
msgid "Remove CA from project"
msgstr ""

#: barbican/api/controllers/cas.py:161
msgid "Set preferred project CA"
msgstr ""

#: barbican/api/controllers/cas.py:191
msgid "Set global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:208
msgid "Unset global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:256
msgid "Certificate Authorities retrieval"
msgstr ""

#: barbican/api/controllers/cas.py:299
msgid "Retrieve global preferred CA"
msgstr ""

#: barbican/api/controllers/cas.py:313
msgid "Retrieve project preferred CA"
msgstr ""

#: barbican/api/controllers/consumers.py:31
msgid "Not Found. Sorry but your consumer is in another castle."
msgstr ""

#: barbican/api/controllers/consumers.py:48
msgid "ContainerConsumer retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:83
msgid "ContainerConsumers(s) retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:122
msgid "ContainerConsumer creation"
msgstr ""

#: barbican/api/controllers/consumers.py:149
msgid "ContainerConsumer deletion"
msgstr ""

#: barbican/api/controllers/containers.py:33
msgid "Not Found. Sorry but your container is in another castle."
msgstr ""

#: barbican/api/controllers/containers.py:61
msgid "Container retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:75
msgid "Container deletion"
msgstr ""

#: barbican/api/controllers/containers.py:122
msgid "Containers(s) retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:160
msgid "Container creation"
msgstr ""

#: barbican/api/controllers/containers.py:188
msgid "Secret provided for '{secret_name}' doesn't exist."
msgstr ""

#: barbican/api/controllers/orders.py:31
msgid "Not Found. Sorry but your order is in another castle."
msgstr ""

#: barbican/api/controllers/orders.py:37
msgid "Secret metadata expected but not received."
msgstr ""

#: barbican/api/controllers/orders.py:42
msgid "Order update is not supported."
msgstr ""

#: barbican/api/controllers/orders.py:47
msgid "Updates are not supported for order type {0}."
msgstr ""

#: barbican/api/controllers/orders.py:53
msgid "Only PENDING orders can be updated. Order is in the{0} state."
msgstr ""

#: barbican/api/controllers/orders.py:59
msgid "Cannot modify order type."
msgstr ""

#: barbican/api/controllers/orders.py:77
msgid "Order retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:83 barbican/api/controllers/orders.py:180
msgid "Order update"
msgstr ""

#: barbican/api/controllers/orders.py:113
msgid "Order deletion"
msgstr ""

#: barbican/api/controllers/orders.py:153
msgid "Order(s) retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:186
msgid "Order creation"
msgstr ""

#: barbican/api/controllers/secrets.py:36
msgid "Not Found. Sorry but your secret is in another castle."
msgstr ""

#: barbican/api/controllers/secrets.py:42
msgid "Secret already has data, cannot modify it."
msgstr ""

#: barbican/api/controllers/secrets.py:51
msgid ""
"Transport key wrapped session key has been provided to wrap secrets for "
"retrieval, but the transport key id has not been provided."
msgstr ""

#: barbican/api/controllers/secrets.py:83
msgid "Secret retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:156
msgid "Secret payload retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:173
msgid "Secret update"
msgstr ""

#: barbican/api/controllers/secrets.py:183
msgid "Content-Type of '{content_type}' is not supported for PUT."
msgstr ""

#: barbican/api/controllers/secrets.py:210
msgid "Secret deletion"
msgstr ""

#: barbican/api/controllers/secrets.py:245
msgid "Secret(s) retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:298
msgid "Secret creation"
msgstr ""

#: barbican/api/controllers/transportkeys.py:34
msgid "Not Found. Transport Key not found."
msgstr ""

#: barbican/api/controllers/transportkeys.py:50
msgid "Transport Key retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:62
msgid "Transport Key deletion"
msgstr ""

#: barbican/api/controllers/transportkeys.py:94
msgid "Transport Key(s) retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:132
msgid "Transport Key Creation"
msgstr ""

#: barbican/api/controllers/versions.py:33
msgid "Version retrieval"
msgstr ""

#: barbican/api/middleware/context.py:32
msgid ""
"When true, this option sets the owner of an image to be the project. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: barbican/api/middleware/context.py:37
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: barbican/api/middleware/context.py:40
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: barbican/api/middleware/context.py:118
msgid "Problem processing X-Service-Catalog"
msgstr ""

#: barbican/api/middleware/context.py:143
msgid "Missing X-Project-Id"
msgstr ""

#: barbican/common/exception.py:39
msgid "An unknown exception occurred"
msgstr ""

#: barbican/common/exception.py:67
msgid "failure seen - please contact site administrator."
msgstr ""

#: barbican/common/exception.py:86
msgid "Missing required argument."
msgstr ""

#: barbican/common/exception.py:90
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: barbican/common/exception.py:94
#, python-format
msgid "Missing required metadata field for %(required)s"
msgstr ""

#: barbican/common/exception.py:100
#, python-format
msgid "Invalid subject DN: %(subject_dn)s"
msgstr ""

#: barbican/common/exception.py:106
#, python-format
msgid "Invalid container: %(reason)s"
msgstr ""

#: barbican/common/exception.py:112
msgid "Invalid extensions data."
msgstr ""

#: barbican/common/exception.py:118
msgid "Invalid CMC Data"
msgstr ""

#: barbican/common/exception.py:124
#, python-format
msgid "Invalid PKCS10 Data: %(reason)s"
msgstr ""

#: barbican/common/exception.py:130
msgid "Invalid Certificate Request Type"
msgstr ""

#: barbican/common/exception.py:136
msgid "Extensions are not yet supported.  Specify a valid profile instead."
msgstr ""

#: barbican/common/exception.py:143
msgid "Full CMC Requests are not yet supported."
msgstr ""

#: barbican/common/exception.py:149
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: barbican/common/exception.py:154
msgid "An object with the specified identifier was not found."
msgstr ""

#: barbican/common/exception.py:158
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: barbican/common/exception.py:162
msgid "The Store URI was malformed."
msgstr ""

#: barbican/common/exception.py:166
msgid "An object with the same identifier already exists."
msgstr ""

#: barbican/common/exception.py:170
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: barbican/common/exception.py:174
msgid "Permission to write image storage media denied."
msgstr ""

#: barbican/common/exception.py:178
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: barbican/common/exception.py:182
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: barbican/common/exception.py:186
msgid "Authorization failed."
msgstr ""

#: barbican/common/exception.py:190
msgid "You are not authenticated."
msgstr ""

#: barbican/common/exception.py:194 barbican/common/exception.py:202
#: barbican/common/exception.py:211
msgid "You are not authorized to complete this action."
msgstr ""

#: barbican/common/exception.py:198
msgid "Operation is not supported."
msgstr ""

#: barbican/common/exception.py:206
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: barbican/common/exception.py:215
msgid "Data supplied was not valid."
msgstr ""

#: barbican/common/exception.py:219
msgid "No data supplied to process."
msgstr ""

#: barbican/common/exception.py:225
msgid "Sort key supplied was not valid."
msgstr ""

#: barbican/common/exception.py:229
msgid "Unable to filter using the specified range."
msgstr ""

#: barbican/common/exception.py:233
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: barbican/common/exception.py:237
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: barbican/common/exception.py:241
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: barbican/common/exception.py:245
msgid "There was an error migrating the database."
msgstr ""

#: barbican/common/exception.py:249
msgid "There was an error connecting to a server"
msgstr ""

#: barbican/common/exception.py:253
msgid "There was an error configuring the client."
msgstr ""

#: barbican/common/exception.py:257
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:264
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:267
msgid "Provided information too large to process"
msgstr ""

#: barbican/common/exception.py:277
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: barbican/common/exception.py:288
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: barbican/common/exception.py:292
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:297
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: barbican/common/exception.py:301
#, python-format
msgid "Invalid content encoding %(content_encoding)s"
msgstr ""

#: barbican/common/exception.py:305
msgid "Error while attempting to decode payload."
msgstr ""

#: barbican/common/exception.py:309
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:314
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:319
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:324
msgid "Deleting images from this store is not supported."
msgstr ""

#: barbican/common/exception.py:328
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: barbican/common/exception.py:333
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr ""

#: barbican/common/exception.py:337
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: barbican/common/exception.py:341
msgid "Received invalid HTTP redirect."
msgstr ""

#: barbican/common/exception.py:345
msgid "Response from Keystone does not contain a Barbican endpoint."
msgstr ""

#: barbican/common/exception.py:350
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: barbican/common/exception.py:356
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: barbican/common/exception.py:360
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: barbican/common/exception.py:368
msgid "Failed to validate JSON information: "
msgstr ""

#: barbican/common/exception.py:369
msgid "Provided object does not match schema '{schema}': {reason}"
msgstr ""

#: barbican/common/exception.py:377
#, python-format
msgid ""
"No support for value set on field '%(field)s' on schema '%(schema)s': "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:379
msgid "Provided field value is not supported"
msgstr ""

#: barbican/common/exception.py:388
#, python-format
msgid ""
"Feature not implemented for value set on field '%(field)s' on schema "
"'%(schema)s': %(reason)s"
msgstr ""

#: barbican/common/exception.py:397
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: barbican/common/exception.py:401
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Barbican."
msgstr ""

#: barbican/common/exception.py:406
msgid "The provided image is too large."
msgstr ""

#: barbican/common/exception.py:410
#, python-format
msgid ""
"Container %(container_id)s does not exist for stored key certificate "
"generation."
msgstr ""

#: barbican/common/exception.py:415
#, python-format
msgid ""
"Container %(container_id)s does not reference a private key needed for "
"stored key certificate generation."
msgstr ""

#: barbican/common/exception.py:420
#, python-format
msgid "The provided UUID in the URI (%(uuid_string)s) is malformed."
msgstr ""

#: barbican/common/exception.py:422
msgid "The provided UUID in the URI is malformed."
msgstr ""

#: barbican/common/exception.py:427
#, python-format
msgid "Invalid CA_ID: %(ca_id)s"
msgstr ""

#: barbican/common/exception.py:428
msgid "The ca_id provided in the request is invalid"
msgstr ""

#: barbican/common/exception.py:433
#, python-format
msgid "CA specified by ca_id %(ca_id)s not defined for project: %(project_id)s"
msgstr ""

#: barbican/common/exception.py:435
msgid "The ca_id provided in the request is not defined for this project"
msgstr ""

#: barbican/common/utils.py:127
msgid "Cannot generate a fullname for a null instance"
msgstr ""

#: barbican/common/validators.py:96
msgid "Bad Container Reference {ref}"
msgstr ""

#: barbican/common/validators.py:106
msgid "Container Not Found"
msgstr ""

#: barbican/common/validators.py:110
msgid "Container Wrong Type"
msgstr ""

#: barbican/common/validators.py:145
msgid "{schema_name}' within '{parent_schema_name}"
msgstr ""

#: barbican/common/validators.py:239
msgid "If 'payload' specified, must be non empty"
msgstr ""

#: barbican/common/validators.py:247
msgid "payload must be provided when payload_content_type is specified"
msgstr ""

#: barbican/common/validators.py:255
msgid "payload_content_type is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:281 barbican/common/validators.py:581
msgid "Invalid date for 'expiration'"
msgstr ""

#: barbican/common/validators.py:295
msgid "'expiration' is before current time"
msgstr ""

#: barbican/common/validators.py:308
msgid "If 'payload' is supplied, 'payload_content_type' must also be supplied."
msgstr ""

#: barbican/common/validators.py:315
msgid "payload_content_type {supplied} is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:325
msgid "payload_content_encoding is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:341
msgid "Invalid payload for payload_content_encoding"
msgstr ""

#: barbican/common/validators.py:414
msgid "'payload' not allowed for key type order"
msgstr ""

#: barbican/common/validators.py:433
msgid "Only 'application/octet-stream' supported"
msgstr ""

#: barbican/common/validators.py:513
msgid "Bad format"
msgstr ""

#: barbican/common/validators.py:520
msgid "Signing key incorrect"
msgstr ""

#: barbican/common/validators.py:564
msgid "'algorithm' is required field for {0} type order"
msgstr ""

#: barbican/common/validators.py:593
msgid "Must have non-zero positive bit_length to generate secret"
msgstr ""

#: barbican/common/validators.py:601
msgid "Must be a positive integer that is a multiple of 8"
msgstr ""

#: barbican/common/validators.py:609
msgid "Feature not implemented for '{0}' order type"
msgstr ""

#: barbican/common/validators.py:720
msgid "Duplicate reference names are not allowed"
msgstr ""

#: barbican/common/validators.py:732
msgid "Duplicate secret ids are not allowed"
msgstr ""

#: barbican/common/validators.py:743
msgid "Secret_ref does not match the configured hostname, please try again"
msgstr ""

#: barbican/common/validators.py:764
msgid ""
"only 'private_key', 'public_key' and 'private_key_passphrase' reference "
"names are allowed for RSA type"
msgstr ""

#: barbican/common/validators.py:772
msgid ""
"The minimum required reference names are 'public_key' and'private_key' "
"for RSA type"
msgstr ""

#: barbican/common/validators.py:785
msgid ""
"only 'private_key', 'certificate' , 'private_key_passphrase',  or "
"'intermediates' reference names are allowed for Certificate type"
msgstr ""

#: barbican/common/validators.py:793
msgid "The minimum required reference name is 'certificate' for Certificate type"
msgstr ""

#: barbican/common/validators.py:839
msgid "plugin_name must be provided"
msgstr ""

#: barbican/common/validators.py:846
msgid "transport_key must be provided"
msgstr ""

#: barbican/model/models.py:378
msgid "Must supply non-None {0} argument for SecretStoreMetadatum entry."
msgstr ""

#: barbican/model/models.py:594
msgid "Must supply non-None {0} argument for OrderPluginMetadatum entry."
msgstr ""

#: barbican/model/models.py:630
msgid "Must supply non-None {0} argument for OrderBarbicanMetadatum entry."
msgstr ""

#: barbican/model/models.py:798
msgid "Must supply non-None {0} argument for TransportKey entry."
msgstr ""

#: barbican/model/models.py:840
msgid "Must supply Non-None {0} argument for CertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:906
msgid "Must supply non-None {0} argument for CertificateAuthorityMetadatum entry."
msgstr ""

#: barbican/model/models.py:953
msgid "Must supply non-None {0} argument for ProjectCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:1002
msgid "Must supply non-None {0} argument for PreferredCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:1056
msgid "Must supply non-None {0} argument for SecretACL entry."
msgstr ""

#: barbican/model/models.py:1132
msgid "Must supply non-None {0} argument for ContainerACL entry."
msgstr ""

#: barbican/model/models.py:1196
msgid "Must supply non-None {0} argument for SecretACLUser entry."
msgstr ""

#: barbican/model/models.py:1233
msgid "Must supply non-None {0} argument for ContainerACLUser entry."
msgstr ""

#: barbican/model/repositories.py:170
msgid "No SQL connection configured"
msgstr ""

#: barbican/model/repositories.py:184
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: {error}"
msgstr ""

#: barbican/model/repositories.py:367
msgid "Must supply non-None {entity_name}."
msgstr ""

#: barbican/model/repositories.py:373
msgid "Must supply {entity_name} with id=None (i.e. new entity)."
msgstr ""

#: barbican/model/repositories.py:451
msgid "{entity_name} status is required."
msgstr ""

#: barbican/model/repositories.py:456
msgid "Invalid status '{status}' for {entity_name}."
msgstr ""

#: barbican/model/repositories.py:476
msgid "{entity_name} is missing query build method for get project entities."
msgstr ""

#: barbican/model/repositories.py:528
#, python-format
msgid "Error deleting project entities for project_id=%s"
msgstr ""

#: barbican/model/repositories.py:564
msgid "No {entity_name} found with keystone-ID {id}"
msgstr ""

#: barbican/model/repositories.py:695
msgid "No secret found with secret-ID {id}"
msgstr ""

#: barbican/model/repositories.py:787
msgid "Tried to register crypto plugin with null or empty name."
msgstr ""

#: barbican/model/repositories.py:1185
msgid "No container found with container-ID {id}"
msgstr ""

#: barbican/model/repositories.py:1262
msgid "Could not find {entity_name}"
msgstr ""

#: barbican/model/repositories.py:1990
msgid "No {entity} found with ID {id}"
msgstr ""

#: barbican/model/repositories.py:1996
msgid "Entity ID {entity_id} not found"
msgstr ""

#: barbican/model/repositories.py:2002
msgid "No entities of type {entity_name} found"
msgstr ""

#: barbican/model/repositories.py:2008
msgid "Entity '{entity_name}' already exists"
msgstr ""

#: barbican/openstack/common/gettextutils.py:305
msgid "Message objects do not support addition."
msgstr ""

#: barbican/openstack/common/gettextutils.py:315
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: barbican/openstack/common/periodic_task.py:46
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: barbican/openstack/common/processutils.py:90
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: barbican/openstack/common/processutils.py:99
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: barbican/openstack/common/processutils.py:114
#, python-format
msgid "Result was %s"
msgstr ""

#: barbican/openstack/common/processutils.py:128
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: barbican/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: barbican/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: barbican/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: barbican/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: barbican/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: barbican/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: barbican/plugin/dogtag.py:44
msgid "Path to PEM file for authentication"
msgstr ""

#: barbican/plugin/dogtag.py:47
msgid "Hostname for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:50
msgid "Port for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:52
msgid "Path to the NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:54
msgid "Password for NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:56
msgid "Profile for simple CMC requests"
msgstr ""

#: barbican/plugin/dogtag.py:59
msgid "List of automatically approved enrollment profiles"
msgstr ""

#: barbican/plugin/dogtag.py:73
msgid "nss_password is required"
msgstr ""

#: barbican/plugin/dogtag.py:88
msgid "pem_path is required"
msgstr ""

#: barbican/plugin/dogtag.py:99
msgid "Invalid algorithm passed in"
msgstr ""

#: barbican/plugin/dogtag.py:103
msgid "Operation not supported by Dogtag Plugin"
msgstr ""

#: barbican/plugin/dogtag.py:361
msgid ""
"Passphrase encryption is not supported for symmetric key generating "
"algorithms."
msgstr ""

#: barbican/plugin/dogtag.py:392
msgid "Passphrase encryption is not supported for DSA algorithm"
msgstr ""

#: barbican/plugin/dogtag.py:509
msgid ""
"DSA keys should not have a passphrase in the database, for being used "
"during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:513
msgid ""
"Secrets of type {secret_type} should not have a passphrase in the "
"database, for being used during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:526
msgid ""
"Encryption using session key is not supported when retrieving a "
"{secret_type} key."
msgstr ""

#: barbican/plugin/dogtag.py:555
msgid "Exception thrown by enroll_cert: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:586
msgid "{request} not found for {operation} for order_id {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:638
msgid "No request found for request_id {request_id} for order {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:664
msgid ""
"Request {request_id} reports status_complete, but no cert_id has been "
"returned"
msgstr ""

#: barbican/plugin/dogtag.py:675
msgid "Certificate not found for cert_id: {cert_id}"
msgstr ""

#: barbican/plugin/dogtag.py:685
msgid "Invalid request_status returned by CA"
msgstr ""

#: barbican/plugin/dogtag.py:802
msgid "No profile_id specified"
msgstr ""

#: barbican/plugin/dogtag.py:854
msgid "No request returned in enrollment_results"
msgstr ""

#: barbican/plugin/dogtag.py:904
msgid "request_id {req_id} returns COMPLETE but no cert returned"
msgstr ""

#: barbican/plugin/dogtag.py:916
msgid "Invalid request_status {status} for request_id {request_id}"
msgstr ""

#: barbican/plugin/dogtag.py:949
msgid "Modify request: unable to cancel: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:980
msgid "no request found for this order"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:47
msgid "Username for authenticating with KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:51
msgid "Password for authenticating with KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:55
msgid "Address of the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:59
msgid "Port for the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:63
msgid "SSL version, maps to the module ssl's constants"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:67
msgid "File path to concatenated \"certification authority\" certificates"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:72
msgid "File path to local client certificate"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:76
msgid "File path to local client certificate keyfile"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:172
msgid ""
"An unsupported algorithm {algorithm} was passed to the "
"'generate_symmetric_key' method"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:230
msgid ""
"An unsupported algorithm {algorithm} was passed to the "
"'generate_asymmetric_key' method"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:236
msgid ""
"KMIP plugin does not currently support protecting the private key with a "
"passphrase"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:305
msgid "Secret object type {object_type} is not supported"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:398
msgid ""
"Unknown key value type received from KMIP server, expected "
"{key_value_struct} or {key_value_string}, received: {key_value_type}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:592
msgid "Status: {status}, Reason: {reason}, Message: {message}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:616
msgid "Bad key file permissions found, expected 400 for path: {file_path}"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:35
msgid "Path to CA certicate file"
msgstr ""

#: barbican/plugin/snakeoil_ca.py:37
msgid "Path to CA certificate key file"
msgstr ""

#: barbican/plugin/symantec.py:34
msgid "Symantec username for authentication"
msgstr ""

#: barbican/plugin/symantec.py:36
msgid "Symantec password for authentication"
msgstr ""

#: barbican/plugin/symantec.py:38
msgid "Domain of Symantec API"
msgstr ""

#: barbican/plugin/symantec.py:54
msgid "username is required"
msgstr ""

#: barbican/plugin/symantec.py:57
msgid "password is required"
msgstr ""

#: barbican/plugin/symantec.py:60
msgid "url is required"
msgstr ""

#: barbican/plugin/crypto/crypto.py:27
msgid "Crypto plugin not found."
msgstr ""

#: barbican/plugin/crypto/crypto.py:32
#: barbican/plugin/interface/certificate_manager.py:157
#: barbican/plugin/interface/certificate_manager.py:171
#: barbican/plugin/interface/certificate_manager.py:185
#: barbican/plugin/interface/secret_store.py:125 barbican/tasks/common.py:63
#: barbican/tasks/common.py:64 barbican/tests/tasks/test_common.py:32
#: barbican/tests/tasks/test_common.py:33
msgid "Unknown"
msgstr ""

#: barbican/plugin/crypto/crypto.py:34
msgid "Failed to bind kek metadata for plugin: {name}"
msgstr ""

#: barbican/plugin/crypto/crypto.py:44
msgid "Could not generate private key"
msgstr ""

#: barbican/plugin/crypto/manager.py:34
#: barbican/plugin/interface/certificate_manager.py:48
#: barbican/plugin/interface/secret_store.py:37
msgid "Extension namespace to search for plugins."
msgstr ""

#: barbican/plugin/crypto/manager.py:38
msgid "List of crypto plugins to load."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:137
msgid "Path to vendor PKCS11 library"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:139
msgid "Password to login to PKCS11 session"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:141
msgid "Master KEK label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:143
msgid "Master KEK length in bytes."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:145
msgid "HMAC label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:235
msgid "More than one key found for label"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:239
msgid "General exception"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:258
msgid "library_path is required"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:676
msgid "Feature not implemented for PKCS11"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:33
msgid "Key encryption key to be used by Simple Crypto Plugin"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:48
msgid "KEK not yet created."
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:62
msgid "Unencrypted data must be a byte type, but was {unencrypted_type}"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:132
msgid "Passphrase not supported for DSA key"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:52
#: barbican/plugin/interface/certificate_manager.py:72
msgid "List of certificate plugins to load."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:68
msgid "Extension namespace to search for eventing plugins."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:117
msgid "Certificate plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:121
msgid "Certificate plugin not found or configured."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:128
msgid "Certificate plugin not found for \"{ca_id}\"."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:137
msgid "Certificate event plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:141
msgid "Certificate event plugin not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:149
msgid "Certificate status of {status} not supported"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:159
msgid "Problem seen during certificate processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:173
msgid "Problem with data in certificate request - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:187
msgid "Invalid operation requested - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:41
msgid "List of secret store plugins to load."
msgstr ""

#: barbican/plugin/interface/secret_store.py:51
msgid "No plugin was found that could support your request"
msgstr ""

#: barbican/plugin/interface/secret_store.py:56
msgid "Secret store plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:59
msgid "Secret store plugin not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:65
msgid "Secret store plugin not found for requested operation."
msgstr ""

#: barbican/plugin/interface/secret_store.py:75
msgid "A Content-Type of '{content_type}' for secrets is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:80
msgid "content-type of '{content_type}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:92
msgid "Secret Content-Encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:97
msgid "content-encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:106
msgid "No secret information provided to encrypt."
msgstr ""

#: barbican/plugin/interface/secret_store.py:113
msgid ""
"Text-based binary secret payloads must specify a content-encoding of "
"'base64'"
msgstr ""

#: barbican/plugin/interface/secret_store.py:119
msgid "Encoding type must be 'base64' for text-based payloads."
msgstr ""

#: barbican/plugin/interface/secret_store.py:127
msgid "Problem seen during crypto processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:136
#: barbican/plugin/interface/secret_store.py:141
msgid "Problem decoding payload"
msgstr ""

#: barbican/plugin/interface/secret_store.py:149
msgid "Secret Accept of '{accept}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:158
msgid "Not Found. Sorry but your secret is in another castle"
msgstr ""

#: barbican/plugin/interface/secret_store.py:164
msgid "No secret information found"
msgstr ""

#: barbican/plugin/interface/secret_store.py:170
msgid "Requested algorithm is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:175
msgid "Secret algorithm of '{algorithm}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:185
msgid "No secret store plugins have been configured"
msgstr ""

#: barbican/plugin/interface/secret_store.py:193
msgid ""
"The requested Store Plugin {plugin_name} is not currently available. This"
" is probably a server misconfiguration."
msgstr ""

#: barbican/queue/__init__.py:36
msgid "True enables queuing, False invokes workers synchronously"
msgstr ""

#: barbican/queue/__init__.py:39
msgid "Queue namespace"
msgstr ""

#: barbican/queue/__init__.py:41
msgid "Queue topic name"
msgstr ""

#: barbican/queue/__init__.py:43
msgid "Version of tasks invoked via queue"
msgstr ""

#: barbican/queue/__init__.py:45
msgid "Server name for RPC task processing server"
msgstr ""

#: barbican/queue/__init__.py:56
msgid "True enables keystone notification listener  functionality."
msgstr ""

#: barbican/queue/__init__.py:59
msgid ""
"The default exchange under which topics are scoped. May be overridden by "
"an exchange name specified in  the transport_url option."
msgstr ""

#: barbican/queue/__init__.py:63
msgid ""
"Keystone notification queue topic name. This name needs to match one of "
"values mentioned in Keystone deployment's 'notification_topics' "
"configuration e.g.    notification_topics=notifications,     "
"barbican_notificationsMultiple servers may listen on a topic and messages"
"  will be dispatched to one of the servers in a round-robin fashion. "
"That's why Barbican service  should have its own dedicated notification "
"queue so  that it receives all of Keystone notifications."
msgstr ""

#: barbican/queue/__init__.py:75
msgid ""
"True enables requeue feature in case of notification processing error. "
"Enable this only when underlying transport supports this feature."
msgstr ""

#: barbican/queue/__init__.py:79
msgid "Version of tasks invoked via notifications"
msgstr ""

#: barbican/queue/__init__.py:81
msgid ""
"Define the number of max threads to be used for notification server "
"processing functionality."
msgstr ""

#: barbican/queue/retry_scheduler.py:40
msgid "Seconds (float) to wait before starting retry scheduler"
msgstr ""

#: barbican/queue/retry_scheduler.py:43
msgid "Seconds (float) to wait between periodic schedule events"
msgstr ""

#: barbican/tasks/keystone_consumer.py:36
msgid "Project cleanup via Keystone notifications"
msgstr ""

#: barbican/tasks/resources.py:233
msgid "Process TypeOrder"
msgstr ""

#: barbican/tasks/resources.py:301 barbican/tasks/resources.py:348
msgid "Order type \"{order_type}\" not implemented."
msgstr ""

#: barbican/tasks/resources.py:319
msgid "Update Order"
msgstr ""

#: barbican/tasks/resources.py:367
msgid "Check Certificate Order Status"
msgstr ""

#: barbican/tasks/resources.py:398
msgid "Order type \"{order_type}\" not supported."
msgstr ""

#: barbican/tests/tasks/test_resources.py:218
#: barbican/tests/tasks/test_resources.py:419
msgid "Process TypeOrder failure seen - please contact site administrator."
msgstr ""

#: barbican/tests/tasks/test_resources.py:357
msgid "Update Order failure seen - please contact site administrator."
msgstr ""

